version: '3'

tasks:
  setup:
    desc: Install dependencies
    cmds:
      - pipenv install --dev

  generate:
    desc: Compiles .proto files into the generated/ folder
    cmds:
      - mkdir -p generated
      - pipenv run python -m grpc_tools.protoc -I../protos --python_out=./generated --grpc_python_out=./generated ../protos/pharmacy.proto
      - touch generated/__init__.py
      - sed -i 's/import pharmacy_pb2 as pharmacy__pb2/from . import pharmacy_pb2 as pharmacy__pb2/' generated/pharmacy_pb2_grpc.py

  migrate:
    desc: Apply Alembic database migrations
    dir: '{{.TASKFILE_DIR}}'
    cmds:
      - PYTHONPATH=. pipenv run alembic upgrade head

  run:
    desc: Run the gRPC server locally
    cmds:
      - PYTHONPATH=. pipenv run python -m app.main

  run:dev:
    desc: Run the gRPC server locally (dev alias)
    cmds:
      - PYTHONPATH=. pipenv run python -m app.main