"""auto migration

Revision ID: bcc9d1719db1
Revises: fbe68b6c131a
Create Date: 2026-04-27 08:02:49.889599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcc9d1719db1'
down_revision: Union[str, None] = 'fbe68b6c131a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admission_stays',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('bed_id', sa.String(), nullable=False),
    sa.Column('bed_category', sa.String(), nullable=False),
    sa.Column('bed_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admission_stays_patient_id'), 'admission_stays', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admission_stays_patient_id'), table_name='admission_stays')
    op.drop_table('admission_stays')
    # ### end Alembic commands ###
