version: '3'

dotenv: ['./hospital-root/.env']
env:
  DOCKER_API_VERSION: "1.41"


includes:
  patient:
    taskfile: ./hospital-root/patient_service/Taskfile.yml
    dir: ./hospital-root/patient_service
  clinical:
    taskfile: ./hospital-root/clinical_service/Taskfile.yml
    dir: ./hospital-root/clinical_service
  pharmacy:
    taskfile: ./hospital-root/pharmacy_service/Taskfile.yml
    dir: ./hospital-root/pharmacy_service
  laboratory:
    taskfile: ./hospital-root/laboratory_service/Taskfile.yml
    dir: ./hospital-root/laboratory_service
  master_data:
    taskfile: ./hospital-root/master_data_service/Taskfile.yml
    dir: ./hospital-root/master_data_service
  billing:
    taskfile: ./hospital-root/billing_service/Taskfile.yml
    dir: ./hospital-root/billing_service
  aggregator:
    taskfile: ./hospital-root/aggregator_service/Taskfile.yml
    dir: ./hospital-root/aggregator_service

tasks:

  all:migrate-generate:
    desc: "Generate migrations for all services"
    vars:
      MSG: "auto migration"
    cmds:
      - task billing:migrate-generate MSG="{{.MSG}}"
      - task laboratory:migrate-generate MSG="{{.MSG}}"
      - task master_data:migrate-generate MSG="{{.MSG}}"
      - task patient:migrate-generate MSG="{{.MSG}}"
      - task pharmacy:migrate-generate MSG="{{.MSG}}"

  all:generate:
    desc: Regenerate all gRPC definitions across all microservices
    cmds:
      - task: master_data:generate
      - task: patient:generate
      - task: clinical:generate
      - task: pharmacy:generate
      - task: laboratory:generate
      - task: billing:generate
      - task: aggregator:generate
  all:install:
    desc: Install dependencies for all services
    cmds:
      - task: master_data:setup
      - task: patient:setup
      - task: clinical:setup
      - task: pharmacy:setup
      - task: laboratory:setup
      - task: billing:setup
      - task: aggregator:setup
  all:migrate:
    desc: Run standard migrations across all services sequentially
    cmds:
      - task: master_data:migrate
      - task: patient:migrate
      - task: clinical:migrate
      - task: pharmacy:migrate
      - task: laboratory:migrate
      - task: billing:migrate

  just:
    desc: Iterates through services and runs external pack build commands
    cmds:
      - task: build:pack
        vars: { SVC: "master_data_service", IMG: "hms-master-data-service:latest" }

  build:
    desc: Iterates through services and runs external pack build commands
    cmds:
      - task: build:pack
        vars: { SVC: "master_data_service", IMG: "hms-master-data-service:latest" }
      - task: build:pack
        vars: { SVC: "patient_service", IMG: "hms-patient-service:latest" }
      - task: build:pack
        vars: { SVC: "clinical_service", IMG: "hms-clinical-service:latest" }
      - task: build:pack
        vars: { SVC: "pharmacy_service", IMG: "hms-pharmacy-service:latest" }
      - task: build:pack
        vars: { SVC: "laboratory_service", IMG: "hms-laboratory-service:latest" }
      - task: build:pack
        vars: { SVC: "aggregator_service", IMG: "hms-aggregator-service:latest" }

  build:pack:
    internal: true
    cmds:
      - pack build {{.IMG}} --path ./hospital-root/{{.SVC}} --builder paketobuildpacks/builder-noble-base --run-image my-ubuntu-run:latest

  up:
    desc: Starts the infrastructure and all services in detached mode
    dir: ./hospital-root
    cmds:
      - docker-compose up -d

  down:
    desc: Stops and removes all containers and volumes
    dir: ./hospital-root
    cmds:
      - docker-compose down -v

  logs:
    desc: Tails logs for all services
    dir: ./hospital-root
    cmds:
      - docker-compose logs -f
