"""create pharmacy tables

Revision ID: c9caa56b11e9
Revises: 
Create Date: 2026-04-25 03:10:40.330690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9caa56b11e9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pharmaceuticals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('critical_level', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pharmaceuticals_code'), 'pharmaceuticals', ['code'], unique=True)
    op.create_table('medical_lots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('medical_id', sa.String(), nullable=False),
    sa.Column('lot_code', sa.String(), nullable=False),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['medical_id'], ['pharmaceuticals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medical_lots_lot_code'), 'medical_lots', ['lot_code'], unique=True)
    op.create_table('stock_movements',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('medical_id', sa.String(), nullable=False),
    sa.Column('lot_id', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('CHARGE', 'DISCHARGE', name='movementtype'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=True),
    sa.Column('actor_id', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['medical_lots.id'], ),
    sa.ForeignKeyConstraint(['medical_id'], ['pharmaceuticals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_movements')
    op.drop_index(op.f('ix_medical_lots_lot_code'), table_name='medical_lots')
    op.drop_table('medical_lots')
    op.drop_index(op.f('ix_pharmaceuticals_code'), table_name='pharmaceuticals')
    op.drop_table('pharmaceuticals')
    # ### end Alembic commands ###
