"""add_bed_category_to_encounter

Revision ID: 6e8301097e81
Revises: 71c5ce460ae1
Create Date: 2026-04-25 21:41:51.574012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e8301097e81'
down_revision: Union[str, None] = '71c5ce460ae1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('encounters', sa.Column('bed_category', sa.String(length=50), nullable=True))
    op.alter_column('encounters', 'bed_id',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('encounters', 'bed_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.drop_column('encounters', 'bed_category')
    # ### end Alembic commands ###