"""auto migration

Revision ID: 0dadad9aaf92
Revises: 102bf96a6155
Create Date: 2026-04-27 08:04:35.001313
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Identifiers used by Alembic.
revision: str = '0dadad9aaf92'
down_revision: Union[str, None] = '102bf96a6155'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
