"""auto migration

Revision ID: 102bf96a6155
Revises: 60f65fb7783a
Create Date: 2026-04-27 08:04:00.818143
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Identifiers used by Alembic.
revision: str = '102bf96a6155'
down_revision: Union[str, None] = '60f65fb7783a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
