"""auto migration

Revision ID: 60f65fb7783a
Revises: ec57925db5db
Create Date: 2026-04-27 08:02:53.765231
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Identifiers used by Alembic.
revision: str = '60f65fb7783a'
down_revision: Union[str, None] = 'ec57925db5db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
