"""auto migration

Revision ID: 6e72d926c62a
Revises: 0dadad9aaf92
Create Date: 2026-04-29 22:15:21.077964
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Identifiers used by Alembic.
revision: str = '6e72d926c62a'
down_revision: Union[str, None] = '0dadad9aaf92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
