"""create laboratory tables

Revision ID: ec57925db5db
Revises: 
Create Date: 2026-04-25 03:10:54.802336
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Identifiers used by Alembic.
revision: str = 'ec57925db5db'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lab_requests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('admission_id', sa.String(), nullable=True),
    sa.Column('exam_type_id', sa.String(), nullable=False),
    sa.Column('material', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'CANCELLED', name='teststatus'), nullable=False),
    sa.Column('request_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_requests_exam_type_id'), 'lab_requests', ['exam_type_id'], unique=False)
    op.create_index(op.f('ix_lab_requests_patient_id'), 'lab_requests', ['patient_id'], unique=False)
    op.create_table('lab_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('request_id', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('result_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('technician_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['lab_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_results_request_id'), 'lab_results', ['request_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lab_results_request_id'), table_name='lab_results')
    op.drop_table('lab_results')
    op.drop_index(op.f('ix_lab_requests_patient_id'), table_name='lab_requests')
    op.drop_index(op.f('ix_lab_requests_exam_type_id'), table_name='lab_requests')
    op.drop_table('lab_requests')
    # ### end Alembic commands ###
