api = "0.9"

[extension]
  id = "taha2samy/gcc-extension"
  version = "0.0.1"
  name = "GCC Extension for UBI"

[[stacks]]
  id = "io.buildpacks.stacks.ubi8"

[[stacks]]
  id = "io.buildpacks.stacks.ubi9"