version: '3'

tasks:
  install:
    desc: "Runs pipenv install"
    cmds:
      - pipenv install --dev

  run:dev:
    desc: "Starts the GraphQL API locally with uvicorn"
    cmds:
      - pipenv run python -m app.main

  test:
    desc: "Executes unit and integration tests"
    cmds:
      - pipenv run pytest

  generate:
    desc: "Compiles .proto files into the generated/ folder"
    cmds:
      - pipenv run python -m grpc_tools.protoc -I../protos --python_out=generated --grpc_python_out=generated ../protos/clinical.proto ../protos/patient.proto
      - sed -i 's/import clinical_pb2/from . import clinical_pb2/' generated/clinical_pb2_grpc.py
      - sed -i 's/import patient_pb2/from . import patient_pb2/' generated/patient_pb2_grpc.py
