CREATE DATABASE IF NOT EXISTS patient_db;

CREATE DATABASE IF NOT EXISTS clinical_db;

CREATE DATABASE IF NOT EXISTS pharmacy_db;

CREATE DATABASE IF NOT EXISTS aggregator_db;

CREATE DATABASE IF NOT EXISTS laboratory_db;

CREATE DATABASE IF NOT EXISTS reference_db;

CREATE DATABASE IF NOT EXISTS keycloak_db;

CREATE DATABASE IF NOT EXISTS billing_db;