version: '3'

includes:
  clinical: ./clinical_service
  patient: ./patient_service
  pharmacy: ./pharmacy_service

tasks:
  generate:all:
    desc: Regenerate all gRPC definitions across all microservices
    cmds:
      - task: patient:proto
      - task: clinical:proto
      - task: pharmacy:proto
      # Aggregator has its own generation that we haven't included yet, let's just run it manually here
      - mkdir -p aggregator_service/generated
      - pipenv run --cwd aggregator_service python -m grpc_tools.protoc -I./protos --python_out=./aggregator_service/generated --grpc_python_out=./aggregator_service/generated ./protos/patient.proto ./protos/clinical.proto ./protos/pharmacy.proto
      - touch aggregator_service/generated/__init__.py
      - pipenv run --cwd aggregator_service sed -i 's/import patient_pb2 as patient__pb2/from . import patient_pb2 as patient__pb2/' aggregator_service/generated/patient_pb2_grpc.py
      - pipenv run --cwd aggregator_service sed -i 's/import clinical_pb2 as clinical__pb2/from . import clinical_pb2 as clinical__pb2/' aggregator_service/generated/clinical_pb2_grpc.py
      - pipenv run --cwd aggregator_service sed -i 's/import pharmacy_pb2 as pharmacy__pb2/from . import pharmacy_pb2 as pharmacy__pb2/' aggregator_service/generated/pharmacy_pb2_grpc.py

  migrate:all:
    desc: Run standard migrations across all services 
    cmds:
      - pipenv run --cwd patient_service alembic upgrade head
      - pipenv run --cwd clinical_service alembic upgrade head
      - pipenv run --cwd pharmacy_service alembic upgrade head
