"""initial

Revision ID: 0001
Revises: 
Create Date: 2024-05-20 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disease_types',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disease_types_code'), 'disease_types', ['code'], unique=True)
    op.create_table('exam_types',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('procedure_type', sa.Enum('SINGLE_VALUE', 'MULTIPLE_BOOLEAN', 'MANUAL_TEXT', name='proceduretypeenum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_types_code'), 'exam_types', ['code'], unique=True)
    op.create_table('operation_types',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_major', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operation_types_code'), 'operation_types', ['code'], unique=True)
    op.create_table('suppliers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('contact_info', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wards',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('beds_count', sa.Integer(), nullable=False),
    sa.Column('is_opd', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wards_code'), 'wards', ['code'], unique=True)
    op.create_table('diseases',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('disease_type_id', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['disease_type_id'], ['disease_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diseases_code'), 'diseases', ['code'], unique=True)
    op.create_index(op.f('ix_diseases_disease_type_id'), 'diseases', ['disease_type_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_diseases_disease_type_id'), table_name='diseases')
    op.drop_index(op.f('ix_diseases_code'), table_name='diseases')
    op.drop_table('diseases')
    op.drop_index(op.f('ix_wards_code'), table_name='wards')
    op.drop_table('wards')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_operation_types_code'), table_name='operation_types')
    op.drop_table('operation_types')
    op.drop_index(op.f('ix_exam_types_code'), table_name='exam_types')
    op.drop_table('exam_types')
    op.drop_index(op.f('ix_disease_types_code'), table_name='disease_types')
    op.drop_table('disease_types')
    # ### end Alembic commands ###
