"""auto migration

Revision ID: 20515d94c8ba
Revises: c962b288cffd
Create Date: 2026-04-27 08:04:37.336464
"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '20515d94c8ba'
down_revision: Union[str, None] = 'c962b288cffd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
