"""

Revision ID: 33d4d0852d5f
Revises: 
Create Date: 2026-04-27 07:58:30.949098
"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '33d4d0852d5f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bed_categories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bed_categories_name'), 'bed_categories', ['name'], unique=True)
    op.create_table('disease_types',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disease_types_code'), 'disease_types', ['code'], unique=True)
    op.create_table('exam_types',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('procedure_type', sa.Enum('SINGLE_VALUE', 'MULTIPLE_BOOLEAN', 'MANUAL_TEXT', name='proceduretypeenum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_types_code'), 'exam_types', ['code'], unique=True)
    op.create_table('operation_types',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_major', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operation_types_code'), 'operation_types', ['code'], unique=True)
    op.create_table('suppliers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('contact_info', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wards',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('beds_count', sa.Integer(), nullable=False),
    sa.Column('is_opd', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wards_code'), 'wards', ['code'], unique=True)
    op.create_table('beds',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('ward_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'OCCUPIED', 'CLEANING', 'MAINTENANCE', name='bedstatusenum'), nullable=False),
    sa.Column('category_id', sa.String(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['bed_categories.id'], ),
    sa.ForeignKeyConstraint(['ward_id'], ['wards.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'ward_id', name='uq_bed_code_per_ward')
    )
    op.create_index(op.f('ix_beds_category_id'), 'beds', ['category_id'], unique=False)
    op.create_index(op.f('ix_beds_ward_id'), 'beds', ['ward_id'], unique=False)
    op.create_table('diseases',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('disease_type_id', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['disease_type_id'], ['disease_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diseases_code'), 'diseases', ['code'], unique=True)
    op.create_index(op.f('ix_diseases_disease_type_id'), 'diseases', ['disease_type_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_diseases_disease_type_id'), table_name='diseases')
    op.drop_index(op.f('ix_diseases_code'), table_name='diseases')
    op.drop_table('diseases')
    op.drop_index(op.f('ix_beds_ward_id'), table_name='beds')
    op.drop_index(op.f('ix_beds_category_id'), table_name='beds')
    op.drop_table('beds')
    op.drop_index(op.f('ix_wards_code'), table_name='wards')
    op.drop_table('wards')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_operation_types_code'), table_name='operation_types')
    op.drop_table('operation_types')
    op.drop_index(op.f('ix_exam_types_code'), table_name='exam_types')
    op.drop_table('exam_types')
    op.drop_index(op.f('ix_disease_types_code'), table_name='disease_types')
    op.drop_table('disease_types')
    op.drop_index(op.f('ix_bed_categories_name'), table_name='bed_categories')
    op.drop_table('bed_categories')
    # ### end Alembic commands ###
