"""auto migration

Revision ID: a4f47c0dc303
Revises: 33d4d0852d5f
Create Date: 2026-04-27 08:02:57.712307
"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'a4f47c0dc303'
down_revision: Union[str, None] = '33d4d0852d5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
