"""auto migration

Revision ID: b712ac647939
Revises: 20515d94c8ba
Create Date: 2026-04-29 22:15:24.778746
"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'b712ac647939'
down_revision: Union[str, None] = '20515d94c8ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
