"""add_beds_table

Revision ID: c56f9358de58
Revises: 4bbc94edd921
Create Date: 2026-04-25 20:28:15.084435
"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'c56f9358de58'
down_revision: Union[str, None] = '4bbc94edd921'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beds',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('ward_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'OCCUPIED', 'CLEANING', 'MAINTENANCE', name='bedstatusenum'), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['ward_id'], ['wards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_beds_ward_id'), 'beds', ['ward_id'], unique=False)
    # ### end Alembic commands ###

    # --- Seeding Data ---
    import uuid
    connection = op.get_bind()
    wards = connection.execute(sa.text("SELECT id, code, beds_count FROM wards")).fetchall()
    
    bed_data = []
    for ward_id, ward_code, beds_count in wards:
        for i in range(1, beds_count + 1):
            bed_data.append({
                "id": str(uuid.uuid4()),
                "code": f"{ward_code}-B{i:02d}",
                "ward_id": ward_id,
                "status": "AVAILABLE",
                "category": "GENERAL"
            })
    
    if bed_data:
        op.bulk_insert(sa.table('beds',
            sa.column('id', sa.String),
            sa.column('code', sa.String),
            sa.column('ward_id', sa.String),
            sa.column('status', sa.Enum('AVAILABLE', 'OCCUPIED', 'CLEANING', 'MAINTENANCE', name='bedstatusenum')),
            sa.column('category', sa.String)
        ), bed_data)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_beds_ward_id'), table_name='beds')
    op.drop_table('beds')
    # ### end Alembic commands ###
