"""auto migration

Revision ID: c962b288cffd
Revises: a4f47c0dc303
Create Date: 2026-04-27 08:04:03.190797
"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'c962b288cffd'
down_revision: Union[str, None] = 'a4f47c0dc303'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
