name: Build Python with Red Hat UBI

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Image Tag'
        required: true
        default: 'latest'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pack CLI
        uses: buildpacks/github-actions/setup-pack@v5.12.0

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push App
        run: |
          REPO_LOWER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          APP_IMAGE="ghcr.io/${REPO_LOWER}/hms-master-data-service:${{ github.event.inputs.tag }}"
          
          pack build "$APP_IMAGE" \
            --path ./hospital-root/master_data_service \
            --builder "paketobuildpacks/builder-ubi8-base" \
            --buildpack "paketo-buildpacks/python" \
            --run-image "${{ env.CUSTOM_RUN_IMAGE }}" \
            --env "BP_PYTHON_VERSION=3.11" \
            --publish